version: "2"
services: 
    php:
        image: phpmyadmin/phpmyadmin
        links: 
            - mysql:db
    
    mysql:
        image: k0st/alpine-mariadb
        volumes: 
            - .data/mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=camagru
            - MYSQL_USER=rkina
            - MYSQL_PASSWORD=1234

    nginx:
        image: nginx:stable-alpine
        ports: 
            - "81:80"
        volumes: 
            - ./nginx/log:/var/log/nginx
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
